# Generated by Django 3.0.4 on 2020-03-15 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WykazStrona1",
            fields=[
                (
                    "l_p",
                    models.DecimalField(
                        decimal_places=65535,
                        max_digits=65535,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "dane_operacji_jednostka_wykonująca_kod",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "element_operacji_data_wykonania",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "element_operacji_czas_wykonania",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "element_operacji_czas_zakończenia",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "dane_operacji_księga_nr",
                    models.DecimalField(
                        blank=True, decimal_places=65535, max_digits=65535, null=True
                    ),
                ),
                (
                    "element_operacji_czas_wykonania2",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "element_operacji_czas_zakończenia3",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "element_operacji_czas_trwania_w_minutach",
                    models.DecimalField(
                        blank=True, decimal_places=65535, max_digits=65535, null=True
                    ),
                ),
                (
                    "personel_uczestniczący_imiona",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "personel_uczestniczący_nazwisko",
                    models.TextField(blank=True, null=True),
                ),
                ("jednostka_zlecająca_nazwa", models.TextField(blank=True, null=True)),
                (
                    "personel_uczestniczący_kod",
                    models.DecimalField(
                        blank=True, decimal_places=65535, max_digits=65535, null=True
                    ),
                ),
                (
                    "personel_uczestniczący_rola_kod",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "element_operacji_typ_elementu_leczenia",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "dane_pacjenta_identyfikator_pacjenta_mip",
                    models.DecimalField(
                        blank=True, decimal_places=65535, max_digits=65535, null=True
                    ),
                ),
                (
                    "dane_pacjenta_data_urodzenia",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "procedury_medyczne_kod_procedury",
                    models.TextField(blank=True, null=True),
                ),
                ("procedury_medyczne_nazwa", models.TextField(blank=True, null=True)),
            ],
            options={"db_table": "wykaz_strona_1", "managed": False,},
        ),
        migrations.CreateModel(
            name="Jednostka",
            fields=[("kod", models.TextField(primary_key=True, serialize=False)),],
        ),
        migrations.CreateModel(
            name="Lekarz",
            fields=[
                ("kod", models.IntegerField(primary_key=True, serialize=False)),
                ("imiona", models.TextField()),
                ("nazwisko", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Pacjent",
            fields=[
                ("mip", models.IntegerField(primary_key=True, serialize=False)),
                ("data_urodzenia", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Procedura",
            fields=[
                ("kod", models.TextField(primary_key=True, serialize=False)),
                ("nazwa", models.TextField()),
            ],
            options={"ordering": ("kod",),},
        ),
        migrations.CreateModel(
            name="Znieczulenie",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nr", models.PositiveIntegerField()),
                ("poczatek", models.DateTimeField()),
                ("koniec", models.DateTimeField(blank=True, null=True)),
                ("czas_trwania", models.IntegerField(blank=True, null=True)),
                (
                    "jednostka",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="zabiegi.Jednostka",
                    ),
                ),
                ("lekarze", models.ManyToManyField(to="zabiegi.Lekarz")),
                (
                    "pacjent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="zabiegi.Pacjent",
                    ),
                ),
                ("procedury", models.ManyToManyField(to="zabiegi.Procedura")),
            ],
        ),
    ]
